title: Format OFCE
author: XT
version: 0.1.0
quarto-required: ">=1.3.300"
#lang: fr
format:
  revealjs:
    slide-level: 2
    slide-number: c/t
    center: false
    navigation-mode: linear
    code-fold: false
    self-contained: false
    code-link: true
    theme: [simple, ofce-pres.scss]
    width: 960
    height: 530
    pdfSeparateFragments: false
    highlight-style: solarized
transition: slide
transition-speed: fast
number-sections: true
        # fig-asp: 0.61
        # crossref:
        #   fig-prefix: figure
        #   tbl-prefix: tableau
        #   eq-prefix: équation
        #   sec-prefix: section
        #   fig-title: figure
        #   tbl-title: tableau
        #   lof-title: Figures
        #   lot-title: Tableaux
        #   logo: www/ofce.png
        # filters:
        #   - nameref
        #   - fr-nbsp
        #  # - custom-numbered-blocks
        #   - quotes
        # shortcodes:
        # - fontawesome

