# palette_pays <- tibble::tribble(
#   ~label_fr,  ~ISO3,      ~HEX,
#   "Allemagne", "DEU", "#dd0000",
#   "France", "FRA", "#002654",
#   "Espagne", "ESP", "#ffc400",
#   "Italie", "ITA", "#009246",
#   "Belgique", "BEL", "#000000",
#   "Grèce", "GRC", "#0d5eaf",
#   "Portugal", "PRT", "#D3A170",
#   "Grande-Bretagne", "GBR", "#9400D3",
#   "Pays-Bas", "NLD", "#FF9B00",
#   "Irlande", "IRL", "#C0087F",
#   "Autriche", "AUT", "#7A9E1A",
#   "Danemark", "DNK", "#c60c30",
#   "Suède", "SWE", "#009FE3",
#   "Finlande", "FIN", "#846A3B",
#   "Etats-Unis", "USA", "#8C000F",
#   "Union Européenne",  "EU", "#003399",
#   "Zone Euro", "EUZ", "#003399",
#   "Chine", "CHN", "#FBBA00",
#   "Japon", "JPN", "#E30613"
# )

palette_pays <- tibble::tribble(
  ~ISO3,          ~label_fr,        ~label_en,      ~HEX,
  "EUZ",        "Zone euro",      "Euro Area", "#003399",
  "EA",        "Zone euro",      "Euro Area", "#003399",
  "EA12",        "Zone euro",      "Euro Area", "#003399",
  "EA19",        "Zone euro",      "Euro Area", "#003399",
  "EA20",        "Zone euro",      "Euro Area", "#003399",
  "EU", "Union européenne", "European Union", "#003399",
  "EU27_2020", "Union européenne", "European Union", "#003399",
  "USA",       "États-Unis",  "United States", "#8C000F",
  "DEU",        "Allemagne",        "Germany", "#dd0000",
  "FRA",           "France",         "France", "#002654",
  "ITA",           "Italie",          "Italy", "#009246",
  "ESP",          "Espagne",          "Spain", "#ffc400",
  "GBR",      "Royaume-Uni", "United Kingdom", "#9400D3",
  "CHN",            "Chine",          "China", "#E9B959",
  "JPN",            "Japon",          "Japan", "#E30613",
  "RUS",           "Russie",         "Russia", "#6F2DA8",
  "UKR",          "Ukraine",        "Ukraine", "#C65911",
  "AUT",         "Autriche",        "Austria", "#7A9E1A",
  "BEL",         "Belgique",        "Belgium", "#000000",
  "DNK",         "Danemark",        "Denmark", "#c60c30",
  "FIN",         "Finlande",        "Finland", "#662483",
  "GRC",            "Grèce",         "Greece", "#0d5eaf",
  "HUN",          "Hongrie",        "Hungary", "#846A3B",
  "IRL",          "Irlande",        "Ireland", "#BE087F",
  "NLD",         "Pays-Bas",     "Netherlands", "#FF9B00",
  "POL",          "Pologne",         "Poland", "#CA9E67",
  "PRT",         "Portugal",       "Portugal", "#D3A170",
  "SWE",            "Suède",         "Sweden", "#009FE3",
  "NOR",          "Norvège",         "Norway", "#00A19A",
  "ARG",        "Argentine",      "Argentina", "#649FD0",
  "BRA",           "Brésil",         "Brazil", "#0D9C39",
  "CHL",            "Chili",          "Chile", "#1C4294",
  "COL",         "Colombie",       "Colombia", "#F4D000",
  "MEX",          "Mexique",         "Mexico", "#CE1327",
  "PER",            "Pérou",           "Peru", "#DA762B",
  "KOR",        "Corée sud",    "South Korea", "#1C4280",
  "IND",             "Inde",          "India", "#F9B233",
  "IDN",        "Indonésie",      "Indonesia", "#006633",
  "MYS",         "Malaisie",       "Malaysia", "#CBBBA0",
  "PHL",      "Philippines",        "Philippines", "#7E6EDC",
  "THA",        "Thaïlande",       "Thailand", "#A3195B",
  "oth",           "Autres",         "Others", "#999",
  "CHE",           "Suisse",    "Switzerland", "#DF65B0",
  "ISR",           "Israël",         "Israel", "#5a7878")

usethis::use_data(palette_pays, overwrite = TRUE)
