---
title: "Template du graphique de la semaine" # titre du graphique ici
author:
  - name: Prénom Nom
    email: "prenom.nom@sciencespo.fr"
    affiliation: OFCE, Sciences Po Paris
    affiliation-url: "http://www.ofce.fr"
    
description: "Description en moins de 295 caractères"

date: 2026-01-19 # Date de publication 
categories: ["mot-clé 1", "mot-clé 2"] # pour voir la liste des mots clés disponibles, taper ofce::keywords 

extraref:  # Voir aussi (optionnel)
  - texte: "ref 1" ## Texte 1 à afficher
    lien:   "https:://ref1.org" ## lien 1 vers le texte
  - texte: "ref2 " ## Texte 2 à afficher
    lien:   "https:://ref1.org" ## lien 2 vers le texte

urlblog: "https://ofce.github.io/GraphOftheWeek_Relecture/relecture/nom_du_qmd.html"

nb: 99

format: 
  gow-html: default
  gow-typst: default 
  
---


```{r}
#| label: setup
#| echo: false
#| message: false
#| warning: false


# Routine d'initialisation des options de base / Chargement des librairies usuelles

library(tidyverse)
library(ofce)


ofce::init_qmd("rinit_gow.r")


```


```{r}
#| label: Chargement des données et autres outils

data <- iris

palette_iris = c("#CD8C95", "#CD96CD", "#8968CD")

```



```{r}
#| label: code pour le graphique
#| fig-asp: 0.85


## Ne pas oublier d'utiliser les ofce_captions pour la note de lecture 
## Graphiques interactifs possible via girafe, utiliser la fonction girafy du package ofce pour le render

titre <- rmarkdown::metadata$title 

g <- data |> ggplot(aes(x = Sepal.Length,y = Petal.Length)) +
  
  geom_point_interactive(aes(color = Species , size = Petal.Width , tooltip = Petal.Width), shape = 8) +
  
  labs(title = titre , 
       subtitle = "Réalisé par XXXX XXXX" ) +
  
  scale_color_manual(values = palette_iris) +
  
  theme()+ ## le theme ofce s'appliquera automatiquement, tous les changements à la marge doivent être inscrits via la fonction theme()
  
  ofce_caption(
    lecture = "Note sur comment lire le graphique",
    note = "Autres notes" ,
    source = "Les sources des donnéees" ) +
  
  ofce::logo_ofce()
  
  
ofce::girafy(g)




```



