---
title: "Fonts in Quarto"
format: 
  pdf:
     pdf-engine: pdflatex
    
  html:
    mainfont: Stone Sans
    monofont: Fira Code
---

```{r init, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  fig.pos="htb", 
  out.extra="",
  dev="ragg_png",
  out.width="100%",
  fig.showtext=TRUE,
  cache=FALSE)

library(tidyverse)
library(showtext)
library(ofce)
sysfonts::font_add_google("Nunito")
options(ofce.background_color = "#F9F4ED")
options(ofce.base_family = "Nunito")
options(ofce.base_size = 9)
```

## Fonts

Normal text here

-   mainfont: For LaTeX output, the main font family for use with xelatex or lualatex.
    Takes the name of any system font.
    1 2 3 4 5 6 7 8 9 10

-   monofont: For LaTeX output, the monospace font family for use with xelatex or lualatex: take the name of any system font.

## Fonts available in system

```{r}
library(palmerpenguins)

ggplot(penguins |> mutate(body_mass_g = log(body_mass_g))) + 
  geom_boxplot(aes(x=factor(year), y=body_mass_g, col=sex))+
  theme_ofce()
```
